Repository OZ-Coding-School/oz_03_main-002-FE, pull requests merged in 2024-08, with the labels that each got.

#56 Feat: 구글 로그인 기능 추가
  .github/__MACOSX/._ISSUE_TEMPLATE
  .github/__MACOSX/._PULL_REQUEST_TEMPLATE.md
  .github/__MACOSX/ISSUE_TEMPLATE/._Bug.md
  .github/__MACOSX/ISSUE_TEMPLATE/._DocumentationImprovement.md
  .github/__MACOSX/ISSUE_TEMPLATE/._FeatureRequest.md
  .github/__MACOSX/ISSUE_TEMPLATE/._OtherTemplate.md
  .github/__MACOSX/ISSUE_TEMPLATE/._Question.md
  .github/workflows/deploy.yml
  .gitignore
  src/api/axios.ts
  src/pages/Login.tsx
  src/store/useAuthStore.ts
Labels: Feat, Chore

#59 Style: UI 통합
  .github/__MACOSX/ISSUE_TEMPLATE/._Bug.md
  .github/__MACOSX/ISSUE_TEMPLATE/._DocumentationImprovement.md
  .github/__MACOSX/ISSUE_TEMPLATE/._FeatureRequest.md
  .github/__MACOSX/ISSUE_TEMPLATE/._OtherTemplate.md
  .github/__MACOSX/ISSUE_TEMPLATE/._Question.md
  src/App.tsx
  src/components/BottomSheet.tsx
  src/components/BulkDeleteModal.tsx
  src/components/CreateModal.tsx
  src/components/DeleteModal.tsx
  src/components/EditModal.tsx
  src/components/Fridge/FridgeItem.tsx
  src/components/Fridge/FridgeList.tsx
  src/components/RecipeCard.tsx
  src/components/common/GlobalHeader.tsx
  src/components/common/Layout.tsx
  src/components/common/ModalForm.tsx
  src/data/recipeData.json
  src/pages/IngredientDetailList.tsx
  src/pages/IngredientView.tsx
  src/pages/Login.tsx
  src/pages/RecipeDetail.tsx
  src/pages/RecipesView.tsx
  src/pages/Signup.tsx
  src/store/useAuthStore.ts
  src/types/recipeType.ts
  tailwind.config.js
  tsconfig.node.json
Labels: Style

#53 [Fix] 냉장고목록 컨텐츠 하단 짤림 에러 해결 #52
  src/components/Fridge/FridgeList.tsx
  src/index.css
Labels: Fix

#60 [Feat] 구글로그인 API 코드 수정
  src/api/axios.ts
  src/pages/Login.tsx
  vite.config.ts
Labels: Feat

#62 Chore: CD 파일 수정
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  src/components/RecipeCard.tsx
  src/pages/RecipeDetail.tsx
  src/pages/RecipesView.tsx
  src/types/ingredientType.ts
  src/types/recipeType.ts
Labels: Chore

#63 CD 파일 develop -> main 이동
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  src/components/RecipeCard.tsx
  src/pages/RecipeDetail.tsx
  src/pages/RecipesView.tsx
  src/types/ingredientType.ts
  src/types/recipeType.ts
Labels: Chore

#66 Feature/deploy
  src/assets/declarations.d.ts
  src/declarations.d.ts
  src/vite-env.d.ts
  tsconfig.node.json
Labels: Chore
