Repository OZ-Coding-School/oz_03_main-002-FE, pull requests merged in 2024-07, with the labels that each got.

#13 Feature/template
  .github/ISSUE_TEMPLATE/Bug.md
  .github/ISSUE_TEMPLATE/DocumentationImprovement.md
  .github/ISSUE_TEMPLATE/FeatureRequest.md
  .github/ISSUE_TEMPLATE/OtherTemplate.md
  .github/ISSUE_TEMPLATE/Question.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/__MACOSX/._ISSUE_TEMPLATE
  .github/__MACOSX/._PULL_REQUEST_TEMPLATE.md
  .github/__MACOSX/ISSUE_TEMPLATE/._Bug.md
  .github/__MACOSX/ISSUE_TEMPLATE/._DocumentationImprovement.md
  .github/__MACOSX/ISSUE_TEMPLATE/._FeatureRequest.md
  .github/__MACOSX/ISSUE_TEMPLATE/._OtherTemplate.md
  .github/__MACOSX/ISSUE_TEMPLATE/._Question.md
Labels: Docs, Chore

#19 Feat: 로그인, 이메일 로그인 화면 구현
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/assets/google-icon.svg
  src/components/Fridge.tsx
  src/components/Header.tsx
  src/components/NavBar.tsx
  src/index.css
  src/pages/FindEmail.tsx
  src/pages/FindPassword.tsx
  src/pages/IngredientView.tsx
  src/pages/Login.tsx
  src/pages/LoginToEmail.tsx
  src/pages/RecipesDetail.tsx
  src/pages/RecipesView.tsx
  src/pages/Signup.tsx
  src/pages/UserHasFridge.tsx
  src/pages/UserHasIngredient.tsx
  src/pages/UserRecipe.tsx
  src/pages/UserRecipeDetail.tsx
Labels: Feat

#20 Chore: package.json 파일 수정
  package.json
Labels: Chore

#26 Chore: 상태 관리 코드 추가
  package-lock.json
  package.json
  src/store/useAuthStore.ts
Labels: Chore

#24 [Feat] 회원가입 페이지 UI 생성 및 기본 기능 구현
  package-lock.json
  package.json
  src/App.tsx
  src/api/axios.js
  src/components/Header.tsx
  src/components/NavBar.tsx
  src/index.css
  src/pages/Signup.tsx
Labels: Design, Feat

#29 Chore: git Action CI 코드 추가
  .github/workflows/ci.yml
Labels: Chore

#31 [Fix] 회원가입오류 수정
  .eslintrc.cjs
  package-lock.json
  package.json
  postcss.config.js
  src/App.tsx
  src/components/Fridge.tsx
  src/components/Header.tsx
  src/components/NavBar.tsx
  src/data/fridge_ingres.ts
  src/main.tsx
  src/pages/FindEmail.tsx
  src/pages/FindPassword.tsx
  src/pages/IngredientView.tsx
  src/pages/Login.tsx
  src/pages/LoginToEmail.tsx
  src/pages/RecipesDetail.tsx
  src/pages/RecipesView.tsx
  src/pages/Signup.tsx
  src/pages/UserHasFridge.tsx
  src/pages/UserHasIngredient.tsx
  src/pages/UserRecipe.tsx
  src/pages/UserRecipeDetail.tsx
  tailwind.config.js
  tsconfig.app.json
  tsconfig.node.json
  vite.config.ts
Labels: Fix

#32 fix: gitAction CI 파일 수정, App.tsx 파일 수정
  .eslintrc.cjs
  .github/workflows/ci.yml
  package-lock.json
  package.json
  src/App.tsx
  src/components/Header.tsx
  src/store/useFridgeStore.ts
Labels: Fix

#30 Feat: 냉장고 재료관리 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/BottomSheet.tsx
  src/components/CreateModal.tsx
  src/components/DeleteModal.tsx
  src/components/EditModal.tsx
  src/components/Header.tsx
  src/data/IngredientTestData.json
  src/pages/IngredientView.tsx
  src/types/types.ts
  tailwind.config.js
Labels: Feat

#37 Feat: 재료 상세 관리 기능 추가 및 일부 코드 수정
  package-lock.json
  package.json
  src/App.tsx
  src/components/BottomSheet.tsx
  src/components/Calendar.css
  src/components/Calendar.tsx
  src/components/CreateModal.tsx
  src/components/DeleteModal.tsx
  src/components/Header.tsx
  src/pages/IngredientDetailEdit.tsx
  src/pages/IngredientDetailList.tsx
  src/types/types.ts
Labels: Fix, Feat, Refactor, Chore

#36 [Feat] 냉장고 목록 보기 UI 및 기능 일부 추가(로컬)
  src/App.tsx
  src/components/FridgeItem.tsx
  src/components/FridgeList.tsx
  src/components/Header.tsx
  src/components/Slider.css
  src/components/Slider.tsx
  src/components/common/PopupModal.tsx
  src/data/IngredientTestData.json
  src/data/fridgeData.ts
  src/data/fridge_ingres.ts
  src/index.css
  src/store/useFridgeStore.ts
  src/types/fridgeType.ts
Labels: Design, Feat

#39 Feat: ingredient 전역 관리 기능 추가
  .eslintrc.cjs
  src/data/IngredientTestData.json
  src/store/useIngredientStore.ts
  src/types/ingredientType.ts
Labels: Feat, Refactor

#41 [Feat] 냉장고 목록 api 코드 작성 및 테스트
  package-lock.json
  package.json
  src/App.tsx
  src/api/axios.js
  src/api/axios.ts
  src/components/Fridge/FridgeItem.tsx
  src/components/Fridge/FridgeList.tsx
  src/components/Fridge/Slider.css
  src/components/Fridge/Slider.tsx
  src/components/Fridge/modals/AddFridgeModal.tsx
  src/components/Fridge/modals/DeleteFridgeModal.tsx
  src/components/Fridge/modals/EditFridgeModal.tsx
  src/components/FridgeItem.tsx
  src/components/FridgeList.tsx
  src/components/common/GlobalHeader.tsx
  src/components/common/ModalForm.tsx
  src/components/common/PopupModal.tsx
  src/data/fridgeData.json
  src/data/fridgeData.ts
  src/pages/Signup.tsx
  src/store/useAuthStore.ts
  src/store/useFridgeStore.ts
  src/types/fridgeType.ts
Labels: Feat

#42 [Refactor] 글로벌 헤더 추가
  package.json
  src/App.tsx
  src/api/axios.ts
  src/components/Fridge/FridgeList.tsx
  src/components/common/GlobalHeader.tsx
  src/components/common/Layout.tsx
  src/pages/Signup.tsx
Labels: Design, Refactor

#43 Feat: 재료 상세 목록 기능 추가
  package-lock.json
  package.json
  src/App.tsx
  src/components/DeleteModal.tsx
  src/data/fridgeIngredientData.json
  src/pages/IngredientDetailEdit.tsx
  src/pages/IngredientDetailList.tsx
  src/store/useIngredientStore.ts
Labels: Feat, Refactor, Chore

#45 Feat: 재료 관리 페이지 통합
  package-lock.json
  package.json
  src/components/BottomSheet.tsx
  src/components/BulkDeleteModal.tsx
  src/components/Calendar.css
  src/components/CreateModal.tsx
  src/components/DeleteModal.tsx
  src/components/EditModal.tsx
  src/data/IngredientTestData.json
  src/data/fridgeData.json
  src/pages/IngredientDetailList.tsx
  src/pages/IngredientView.tsx
  src/pages/Login.tsx
  src/store/useIngredientStore.ts
  src/types/ingredientType.ts
Labels: Fix, Feat

#44 [Feat] 회원가입 api 기능 추가
  public/defaultUserAvatar.png
  src/App.tsx
  src/components/Header.tsx
  src/components/common/GlobalHeader.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
  src/store/useAuthStore.ts
  src/types/userType.ts
Labels: Design, Feat

#50 [Feat] 냉장고 목록 애니메이션 구현
  src/components/Fridge/FridgeList.tsx
  src/components/Fridge/Slider.css
  src/components/Fridge/Slider.tsx
  src/components/Fridge/modals/DeleteFridgeModal.tsx
  src/components/Fridge/modals/EditFridgeModal.tsx
  src/components/common/Layout.tsx
  src/components/common/ModalForm.tsx
  src/store/useFridgeStore.ts
Labels: Fix, Feat

#54 [긴급] 빌드를 위한 recipe 임시 업로드
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/components/Fridge.tsx
  src/components/Fridge/FridgeList.tsx
  src/components/Fridge/Slider.tsx
  src/components/Fridge/modals/DeleteFridgeModal.tsx
  src/components/Fridge/modals/EditFridgeModal.tsx
  src/components/NavBar.tsx
  src/data/fridge_ingres.ts
  src/data/realistic_combined_cooking_list.json
  src/data/recipeData.json
  src/index.css
  src/pages/FindEmail.tsx
  src/pages/FindPassword.tsx
  src/pages/RecipeDetail.tsx
  src/pages/RecipesView.tsx
  src/pages/UserHasFridge.tsx
  src/pages/UserHasIngredient.tsx
  src/pages/UserRecipe.tsx
  src/pages/UserRecipeDetail.tsx
  src/store/useRecipeStore.ts
  src/types/recipeType.ts
  vite.config.ts
Labels: Feat, Chore
